version: '3.3'

services:
  backend:
    build: ./services/backend
    volumes:
      - ./services/backend/:/usr/src/app/
    ports:
      - 5000:5000

  frontend:
    build: ./services/frontend
    volumes:
      - ./services/frontend/:/usr/src/app/
    ports:
      - 8080:8080
    
